env_id: wireless-sigmap-v0
exp_name: sac_beamforming_hallway_L

replay_buffer_capacity: 25000
total_steps: 10002
random_steps: 1201
training_starts: 1201
ep_len: 200

# Evaluation settings
eval_interval: 400
num_eval_trials: 1
eval_ep_len: 100

# Training settings
actor_learning_rate: 0.0001
critic_learning_rate: 0.0004
alpha_learning_rate: 0.0002
batch_size: 256
num_train_steps_per_env_step: 15

# Actor-critic configuration
hidden_sizes: [256, 256, 256, 256]
discount: 0.90
polyak: 0.95 # soft_target_update_rate
num_critics: 2
num_critic_updates: 5
temperature: 0.1
num_actor_samples: 32
