env_id: wireless-sigmap-v0
exp_name: sac_beamforming_hallway_L

replay_buffer_capacity: 100
total_steps: 9
random_steps: 5
training_starts: 5
ep_len: 4

# Evaluation settings
eval_interval: 2
num_eval_trials: 3
eval_ep_len: 5

# Training settings
actor_learning_rate: 0.0001
critic_learning_rate: 0.0003
alpha_learning_rate: 0.0002
batch_size: 4
num_train_steps_per_env_step: 10

# Actor-critic configuration
hidden_sizes: [256, 256, 256, 256]
discount: 0.90
ema_decay: 0.95 # soft_target_update_rate
num_critics: 2
num_critic_updates: 5
temperature: 0.05
num_actor_samples: 4
saved_path: "./saved_models/"
